Severity Code Description Project File Line Suppression State Error C2676 binary '>': 'sc2::Point3D' does not define this operator or a conversion to a type acceptable to the predefined operator BlankBot C:\Users\VonRansak\Bots\blank-bot\src\Bot.cpp 154